[package]
name = "evilbocchi/serikanum"
version = "1.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "Onoe Serika's go-to big number library for small and large-scale incremental games!"
license = "MIT"
include = ["SerikaNum", "SerikaNum/**", "default.project.json", "LICENSE", "wally.toml"]
exclude = ["*"]

[dependencies]
